[package]
name = "ucc-discord-bot"
version = "0.1.0"
authors = ["tec <tec@ucc.gu.uwa.edu.au>"]
edition = "2018"

[dependencies]
serenity = "0.6.3"
rand = "0.7.0"
lazy_static = "1.3.0"
log = "0.4.8"
simplelog = "0.6.0"
