[package]
name = "ucc-discord-bot"
version = "0.1.0"
authors = ["tec <tec@ucc.gu.uwa.edu.au>"]
edition = "2018"

[dependencies]
serenity = "^0.7.1"
rand = "^0.7.2"
lazy_static = "^1.4.0"
log = "^0.4.8"
simplelog = "^0.7.4"
